Sample workflow for Centos Tink #328
tinkerbell/workflows pull request #5
Opened 2021-01-29 18:25 UTC by Cbkhare

## Description

Sample workflow for centos.

This example used cloud-init implementation,
Tink issue; https://github.com/tinkerbell/tink/issues/328

2021-03-04 21:49 UTC, tstromberg requested changes
Looks like a great effort! I've added some random thoughts from a drive-by reviewer ...

2021-03-04 21:49 UTC, tstromberg commented on centos/README.md
> +# Centos Sample Workflow
Please use the correct capitalization: CentOS (here and elsewhere)

2021-03-04 21:49 UTC, tstromberg commented on centos/README.md
> +This is a sample workflow to provision a Centos machine. This example uses the cloudInit mechanism to make it work.
Should be `cloud-init`? This may be unnecessary for many readers, but it would probably help to have this link to documentation for folks who are not yet familiar with cloud-init - particularly if there is any links that are highly relevant for tinkerbell users.

2021-03-04 21:49 UTC, tstromberg commented on centos/README.md
> +- Place the raw image of the OS inside `OSIE` at location `webroot`. If you prefer to place it somewhere else then please update the template accordingly.
IMHO, you should either indicate how one would modify the template or just strike the second sentence out entirely.

2021-03-08 13:36 UTC, Cbkhare commented on centos/README.md
> +This is a sample workflow to provision a Centos machine. This example uses the cloudInit mechanism to make it work.
I do not have any specific reference for tinkerbell, but as per your suggestion I do have added a link for `clout-init` official documentation. That does have some standard examples.

2021-03-08 13:52 UTC, Cbkhare commented on centos/README.md
> +- Place the raw image of the OS inside `OSIE` at location `webroot`. If you prefer to place it somewhere else then please update the template accordingly.
sure, I have updated the second line to mark which fields are required to be changed.

2021-03-08 14:32 UTC, Cbkhare commented
@tstromberg I have incorporated your changes. But somehow my commits on the branch is not visible in this PR https://github.com/Cbkhare/workflows/tree/centos_sample_workflow_%23328/centos. Let me check, I will update the PR.

2021-03-11 13:52 UTC, merged

2021-03-12 10:11 UTC, Cbkhare commented
created this PR https://github.com/tinkerbell/workflows/pull/7 to address @tstromberg comments.